### ISSUE TITLE
External link

### ISSUE THREAD

**Issue by argenteum** [TheScienceMuseum/web-design-system#9]
Can you add the external link button variant (`.-external`) that we see on the Drupal sites to buttons?

(And therefore also make it available to the WP themes for use) .

E.g. the 'Book now' button on https://www.sciencemuseum.org.uk/see-and-do/wonderlab-equinor-gallery

![Screenshot 2019-08-28 at 11 45 42](https://user-images.githubusercontent.com/27769049/63924095-926edc00-ca3f-11e9-9d20-b3c40471309c.png)

**Comment by tobystokes** [comment]
That icon is now in the set at https://thesciencemuseum.github.io/web-design-system/docs/icons.html
(note todo: update external icon used on collections to match)
To add to a button, you would need to include the svg in it, like examples on 
https://thesciencemuseum.github.io/web-design-system/components/detail/button.html

(the `.external' class doesn't do anything visual, they add the svg the same way)
